version: '3.4'

services:
  discordbot:
    image: ${DOCKER_REGISTRY-}discordbot
    build:
      context: .
      dockerfile: DiscordBot/Dockerfile
    volumes:
      - type: bind
        source: DiscordBot/Defends.csv
        target: /app/Defends.csv
      - type: bind
        source: DiscordBot/DiscordServers.csv
        target: /app/DiscordServers.csv
