version: '3.5'

services:
  discordbot:
    image: ${DOCKER_REGISTRY-}discordbot
    build:
      context: .
      dockerfile: DiscordBot/Dockerfile
    networks:
      db:
        ipv4_address: 172.16.2.121
#    volumes:
#      - type: bind
#        source: DiscordBot/Defends.csv
#        target: /app/Defends.csv
#      - type: bind
#        source: DiscordBot/DiscordServers.csv
#        target: /app/DiscordServers.csv

networks:
  db:
    name: bb-dbs
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.2.0/24"

