/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.ALLIANCE_DIPLOMACY
(
    ID              NUMBER(19)   default "STFC"."ISEQ$$_105342".nextval generated by default on null as identity
        constraint PK_ALLIANCE_DIPLOMACY
        primary key,
    OWNER_ID        NUMBER(19)                                                                               not null
        constraint FK_ALLIANCE_DIPLOMACY_ALLIANCES_OWNER_ID
            references STFC.ALLIANCES
                on delete cascade,
    RELATED_ID      NUMBER(19)                                                                               not null
        constraint FK_ALLIANCE_DIPLOMACY_ALLIANCES_RELATED_ID
            references STFC.ALLIANCES
                on delete cascade,
    RELATIONSHIP_ID NUMBER(10)                                                                               not null
        constraint FK_ALLIANCE_DIPLOMACY_CT_DIPLOMATIC_RELATION_RELATIONSHIP_ID
            references STFC.CT_DIPLOMATIC_RELATION,
    MODIFIED_BY     NVARCHAR2(500),
    MODIFIED_DATE   TIMESTAMP(7) default TO_TIMESTAMP('0001-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF') not null
)
/

create index STFC.IX_ALLIANCE_DIPLOMACY_OWNER_ID
    on STFC.ALLIANCE_DIPLOMACY (OWNER_ID)
/

create index STFC.IX_ALLIANCE_DIPLOMACY_RELATED_ID
    on STFC.ALLIANCE_DIPLOMACY (RELATED_ID)
/

create index STFC.IX_ALLIANCE_DIPLOMACY_RELATIONSHIP_ID
    on STFC.ALLIANCE_DIPLOMACY (RELATIONSHIP_ID)
/

