/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.ALLIANCES
(
    ID                            NUMBER(19)   default "STFC"."ISEQ$$_105337".nextval generated by default on null as identity
        constraint PK_ALLIANCES
        primary key,
    NAME                          NVARCHAR2(2000),
    ACRONYM                       NVARCHAR2(10),
    ALLIANCE_GROUP_ID             NUMBER(19)
        constraint FK_ALLIANCES_ALLIANCE_GROUPS_ALLIANCE_GROUP_ID
            references STFC.ALLIANCE_GROUPS,
    GUILD_ID                      NUMBER(20),
    DEFEND_SCHEDULE_POST_CHANNEL  NUMBER(20),
    DEFEND_SCHEDULE_POST_TIME     NVARCHAR2(10),
    DEFEND_BROADCAST_LEAD_TIME    NUMBER(10),
    NEXT_SCHEDULED_POST           TIMESTAMP(7),
    MODIFIED_BY                   NVARCHAR2(500),
    MODIFIED_DATE                 TIMESTAMP(7) default TO_TIMESTAMP('0001-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF') not null,
    STATUS                        CHAR         default 'A'                                                                 not null,
    ALLIED_BROADCAST_ROLE         NUMBER(20),
    DEFENDBROADCASTPINGFORLOWRISK NUMBER(1),
    DEFENDBROADCASTPINGROLE       NUMBER(20)
)
/

create index STFC.IX_ALLIANCES_ALLIANCE_GROUP_ID
    on STFC.ALLIANCES (ALLIANCE_GROUP_ID)
/

