/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC."AUDIT"
(
    ID               NUMBER(19)   default "STFC"."ISEQ$$_105372".nextval generated by default on null as identity
        constraint PK_AUDIT
        primary key,
    USER_ID          NVARCHAR2(200),
    TYPE             NVARCHAR2(50),
    TABLE_NAME       NVARCHAR2(200),
    DATE_TIME        TIMESTAMP(7)                                                                             not null,
    OLD_VALUES       NVARCHAR2(2000),
    NEW_VALUES       NVARCHAR2(2000),
    AFFECTED_COLUMNS NVARCHAR2(2000),
    PRIMARY_KEY      NVARCHAR2(2000),
    MODIFIED_BY      NVARCHAR2(500),
    MODIFIED_DATE    TIMESTAMP(7) default TO_TIMESTAMP('0001-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF') not null
)
/

