/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.CT_OFFICERS
(
    ID                 NUMBER(19) generated by default on null as identity,
    NAME               VARCHAR2(2000),
    MODIFIED_BY        VARCHAR2(1000),
    MODIFIED_DATE      DATE,
    CAPTAIN_ABILITY    VARCHAR2(1000),
    BRIDGE_ABILITY     VARCHAR2(1000),
    LOWER_DECK_ABILITY VARCHAR2(1000),
    OFFICER_GROUP_ID   NUMBER(19)
        constraint CT_OFFICERS_FK1
            references STFC.CT_OFFICER_GROUP,
    OFFICER_RARITY_ID  NUMBER(19)
        constraint CT_OFFICERS_FK2
            references STFC.CT_OFFICER_RARITY,
    OFFICER_FACTION_ID NUMBER(19)
        constraint CT_OFFICERS_FK3
            references STFC.CT_OFFICER_FACTION,
    ALTERNATE_NAME     VARCHAR2(2000),
    OFFICER_TYPE_ID    NUMBER(19)
        constraint CT_OFFICERS_FK4
            references STFC.CT_OFFICER_TYPE
)
/

create unique index STFC.CT_OFFICERS_PK1
    on STFC.CT_OFFICERS (ID)
/

alter table STFC.CT_OFFICERS
    add constraint CT_OFFICERS_PK
        primary key (ID)
/

