/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.CT_USER_STATUS
(
    ID            NUMBER(19) generated by default on null as identity,
    NAME          VARCHAR2(2000),
    MODIFIED_BY   VARCHAR2(1000),
    MODIFIED_DATE DATE
)
/

create unique index STFC.CT_USER_STATUS_PK1
    on STFC.CT_USER_STATUS (ID)
/

alter table STFC.CT_USER_STATUS
    add constraint CT_USER_STATUS_PK
        primary key (ID)
/

