/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.STARSYSTEMS
(
    ID            NUMBER(19)   default "STFC"."ISEQ$$_105350".nextval generated by default on null as identity
        constraint PK_STARSYSTEMS
        primary key,
    NAME          NVARCHAR2(200)                                                                           not null,
    ZONE_ID       NUMBER(19)                                                                               not null
        constraint FK_STARSYSTEMS_ZONES_ZONE_ID
            references STFC.ZONES,
    RESOURCE_ID   NUMBER(10)
        constraint FK_STARSYSTEMS_CT_RESOURCES_RESOURCE_ID
            references STFC.CT_RESOURCES,
    MODIFIED_BY   NVARCHAR2(500),
    MODIFIED_DATE TIMESTAMP(7) default TO_TIMESTAMP('0001-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF') not null
)
/

create index STFC.IX_STARSYSTEMS_RESOURCE_ID
    on STFC.STARSYSTEMS (RESOURCE_ID)
/

create index STFC.IX_STARSYSTEMS_ZONE_ID
    on STFC.STARSYSTEMS (ZONE_ID)
/

