/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.USERS
(
    ID            NUMBER(19) generated by default on null as identity,
    ALLIANCE_ID   NUMBER(19)
        constraint USERS_ALLIANCE_ID_FK
            references STFC.ALLIANCES,
    USERNAME      VARCHAR2(2000),
    MODIFIED_BY   VARCHAR2(1000),
    MODIFIED_DATE DATE
)
/

create index STFC.USERS_I1
    on STFC.USERS (ALLIANCE_ID)
/

alter table STFC.USERS
add DISCORD_ID NUMBER(20) default null;
/

create unique index STFC.USERS_DISCORD
    on STFC.USERS (discord_id)
/

alter table STFC.USERS
add DISCORD_DATA CLOB default null;
/

alter table STFC.USERS
add USER_STATUS NUMBER(19) default 1 NOT NULL
    constraint FK_USERS_USER_STATUS
        references STFC.CT_USER_STATUS
/

create index STFC.USERS_I2
    on STFC.USERS (USER_STATUS)
/
