/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

create table STFC.ZONES
(
    ID                  NUMBER(19)   default "STFC"."ISEQ$$_105345".nextval generated by default on null as identity
        constraint PK_ZONES
        primary key,
    NAME                NVARCHAR2(200)                                                                           not null,
    "LEVEL"             NUMBER(10)                                                                               not null,
    THREATS             NVARCHAR2(2000),
    DEFEND_DAY_OF_WEEK  NVARCHAR2(15)                                                                            not null,
    DEFEND_UTC_TIME     NVARCHAR2(10)                                                                            not null,
    DEFEND_EASTERN_DAY  NUMBER(10),
    DEFEND_EASTERN_TIME NVARCHAR2(50),
    NOTES               NVARCHAR2(2000),
    OWNER_ID            NUMBER(19)
        constraint FK_ZONES_ALLIANCES_OWNER_ID
            references STFC.ALLIANCES
                on delete set null,
    NEXT_DEFEND         TIMESTAMP(7),
    MODIFIED_BY         NVARCHAR2(500),
    MODIFIED_DATE       TIMESTAMP(7) default TO_TIMESTAMP('0001-01-01 00:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF') not null
)
/

create index STFC.IX_ZONES_OWNER_ID
    on STFC.ZONES (OWNER_ID)
/

