/*
Copyright 2022 Boonebytes

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

GRANT CONNECT TO STFC_DISCORD;

GRANT DELETE ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."AUDIT" TO "STFC_DISCORD";

GRANT SELECT ON "STFC"."CT_ALLIANCE_SERVICE_LEVEL" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."MEMBERS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONES" TO "STFC_DISCORD";
