GRANT DELETE ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."__EFMigrationsHistory" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_DIPLOMACY" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_GROUPS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_INVENTORY" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_INVENTORY_LINE" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCE_SERVICES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ALLIANCES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ALLIANCES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."AUDIT" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."AUDIT" TO "STFC_DISCORD";

GRANT SELECT ON "STFC"."CT_ALLIANCE_SERVICE_LEVEL" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."CT_DIPLOMATIC_RELATION" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."CT_RESOURCES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."DIRECT_MESSAGES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."MEMBERS_AUDIT" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."MEMBERS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."MEMBERS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."STARSYSTEMS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_NEIGHBOURS" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_SERVICE_COST" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONE_SERVICES" TO "STFC_DISCORD";

GRANT DELETE ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT INSERT ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT SELECT ON "STFC"."ZONES" TO "STFC_DISCORD";
GRANT UPDATE ON "STFC"."ZONES" TO "STFC_DISCORD";

GRANT EXECUTE ON STFC.PKG_INVENTORY TO STFC_DISCORD;
GRANT SELECT ON STFC.V_ALLIANCE_INVENTORY_DELTAS TO STFC_DISCORD;